### ISSUE TITLE
大佬好

### ISSUE THREAD

**Issue by Boris-code** [mic1on/person-doc#1]
大佬，请问您的博客用的啥搭建的呀，什么主题

**Comment by mic1on** [comment]
大佬您好，博客采用VuePress+Hero搭建。

**Comment by mic1on** [comment]
> 大佬，请问您的博客用的啥搭建的呀，什么主题



> 大佬，请问您的博客用的啥搭建的呀，什么主题

大佬您好，博客采用VuePress+Hero搭建。

**Comment by Boris-code** [comment]
谢谢大佬
